SpawnRangeMinX: -10
SpawnRangeMaxX: 610
SpawnRangeY: -100
PlayerRadius: 15.0
PlayerMoveRangeMinX: 50
PlayerMoveRangeMaxX: 550
PlayerMoveRangeY: 550 
IsPlayerStartMovePositive: true
EnemySize: 50
EnemyDeadZoneY: 700
EnemyFadeOutTime: 1.0
ParticleCount: 400
ParticleMinSize: 5.0
ParticleMaxSize: 10.0
ParticleMinSpeed: 100.0
ParticleMaxSpeed: 400.0
ParticleLifeTime: 1.0
TabTextMoveSpeed: 80.0
TabTextLifeTime: 1.0
TabTextFontSize: 24.0
TabTextOffsetY: 30.0
GameOverTextPosition:
  x: 300
  y: 300
GameOverTextColor:
  r: 1.0
  g: 0.5
  b: 0.1
  a: 1.0
GameOverTextFontSize: 80.0
GameResultTextPosition:
  x: 300
  y: 420
GameResultTextColor:
  r: 1.0
  g: 1.0
  b: 1.0
  a: 1.0
GameResultTextFontSize: 32.0
GameResultHintTextPosition:
  x: 300
  y: 500
GameResultHintTextColor:
  r: 1.0
  g: 1.0
  b: 1.0
  a: 1.0
GameResultHintTextFontSize: 24.0
GameResultHintTextBlinkSpeed: 3.0
PlayTimeTextPosition:
  x: 300
  y: 50
PlayTimeTextColor:
  r: 1.0
  g: 1.0
  b: 1.0
  a: 1.0
PlayTimeTextFontSize: 40.0
TitleTextPosition:
  x: 300
  y: 300
TitleTextColor:
  r: 1.0
  g: 1.0
  b: 1.0
  a: 1.0
TitleTextFontSize: 100.0
TitleHintTextPosition:
  x: 300
  y: 500
TitleHintTextColor:
  r: 1.0
  g: 1.0
  b: 1.0
  a: 1.0
TitleHintTextFontSize: 40.0
TitleHintTextBlinkSpeed: 3.0